def generate_explanation(company_data, risk_analysis, loan_terms):
    """Generate AI reasoning explanation"""
    
    risk_level = risk_analysis["risk_level"]
    risk_score = risk_analysis["risk_score"]
    
    explanation = f"""
## AI-Powered Credit Decision Reasoning

### Risk Assessment Summary

**Risk Level:** {risk_level}  
**Risk Score:** {risk_score}/100

Based on the comprehensive analysis of {company_data['company_name']}, our AI risk engine has assessed the creditworthiness and structured appropriate loan terms.

---

### Key Decision Factors

#### 1. **Tenor Selection: {loan_terms['tenor']}**

"""
    
    if risk_score > 60:
        explanation += """
The shorter tenor reduces lender exposure given the elevated risk profile. This allows for more frequent covenant monitoring and earlier principal recovery.
"""
    elif risk_score > 35:
        explanation += """
A balanced tenor appropriate for the moderate risk profile, allowing the borrower adequate time for business operations while maintaining lender security.
"""
    else:
        explanation += """
The extended tenor reflects strong creditworthiness and provides the borrower with flexibility for long-term planning and investment.
"""
    
    explanation += f"""

#### 2. **Interest Rate: {loan_terms['interest_margin']}**

"""
    
    if risk_score > 60:
        explanation += """
The premium margin compensates for higher default risk and accounts for industry volatility, leverage concerns, and refinancing risk.
"""
    elif risk_score > 35:
        explanation += """
Market-standard pricing for moderate-risk commercial loans, balancing competitive rates with appropriate risk-adjusted returns.
"""
    else:
        explanation += """
Competitive rate reflecting strong financial position, stable industry fundamentals, and conservative leverage metrics.
"""
    
    explanation += """

#### 3. **Financial Covenants**

The selected covenants ensure:
- Ongoing monitoring of financial health
- Early warning indicators of deteriorating performance
- Protection of lender interests
- Maintenance of borrower discipline

"""
    
    explanation += f"""

#### 4. **Collateral & Security**

First lien position provides:
- Priority claim on all company assets
- Enhanced recovery prospects
- Stronger negotiating position
- Comprehensive security coverage

---

### Risk Factors Considered

"""
    
    for factor in risk_analysis["risk_factors"]:
        explanation += f"- {factor}\n"
    
    explanation += f"""

---

### Final Recommendation

**{risk_analysis['recommendation']}**

This term sheet balances credit risk, market conditions, regulatory requirements, and competitive dynamics to structure a loan that protects lender interests while supporting borrower growth.

---

*This analysis was generated by AURA's AI Credit Decision Engine using machine learning models trained on thousands of commercial loan outcomes.*
"""
    
    return explanation